### ISSUE TITLE
How can I enable it in the macOS version?

### ISSUE THREAD

**Issue by llity** [dracula/zotero#2]
Maybe it cannot apply on the macOS version Zotero?

Thanks.

**Comment by bezmi** [comment]
On Linux (which I assume is similar), I had a hidden folder `.zotero` in my home directory. I navigated to `~/.zotero/zotero/{random_code}.default/` and made the `chrome` directory, then pasted the file.

**Comment by omanuelcosta** [comment]
> On Linux (which I assume is similar), I had a hidden folder `.zotero` in my home directory. I navigated to `~/.zotero/zotero/{random_code}.default/` and made the `chrome` directory, then pasted the file.

Topic closed due to solution by @bezmi

added step-by-step in the README.

**Comment by maurice-schleussinger** [comment]
That is not the correct folder for macOS, as documented [here](https://www.zotero.org/support/kb/profile_directory). Creating a `chrome` folder in `/Users/<username>/Library/Application Support/Zotero/Profiles/<randomstring>` with the CSS file works. 🙂
